from . import home
from . import problemlist
from . import problem
from . import problemadd
from . import problemedit
from . import problemdel
from . import newsubmit
from . import status
from . import record
from . import login
from . import register
